const ERROR_CODES = {
  INVALID_ARGUMENTS: 'INVALID_ARGUMENTS',
  UNKNOWN_DOMAIN: 'UNKOWN_DOMAIN',
  UNKNOWN_VERSION: 'UNKOWN_VERSION',
  VERSION_EXISTS: 'VERSION_EXISTS'
}

exports.ERROR_CODES = ERROR_CODES
